title: Jorge de los Santos
description: Software Architect | Platform Engineer | Blockchain Developer
author: Jorge de los Santos
email: contact@tebayoso.dev
url: https://tebayoso.github.io
baseurl: ""

# Social
twitter_username: tebayoso
github_username: tebayoso
linkedin_username: tebayoso

# Build settings
theme: null
plugins: []
